# -*- coding: utf-8 -*-
"""CODIGOESTADISTICO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUD6kWUfyodYQWw9K_Y3Q6cXkkT5xm08
"""

import pandas as pd

data1 = {
    'VARIABLE': ['Fecha', 'Categoría', 'Código', 'Nombre', 'Sector', 'Ubicación', 'Superficie', 'UICN', 'Balance C.', 'Fecha E.C.', 'Balance M.', 'Fecha E.M.'],
    'DESCRIPCIÓN': ['Fecha de corte', 'Categoría de la ANP', 'Código de la ANP', 'Nombre de la ANP', 'Sector de la ANP', 'Ubicación de la ANP', 'Superficie de la ANP', 'UICN de la ANP', 'Balance C. de la ANP', 'Fecha E.C. de la ANP', 'Balance M. de la ANP', 'Fecha E.M. de la ANP'],
    'TIPO DE DATO': ['Fecha', 'Categórico', 'Entero', 'Texto', 'Texto', 'Texto', 'Flotante', 'Texto', 'Entero', 'Fecha', 'Entero', 'Fecha'],
    'TAMAÑO': [None, None, None, None, None, None, None, None, None, None, None, None],
    'RECURSO RELACIONADO': [None, None, None, None, None, None, None, None, None, None, None, None],
    'INFORMACIÓN ADICIONAL': [None, None, None, None, None, None, None, None, None, None, None, None]
}

# Crear DataFrame
df1 = pd.DataFrame(data1)

# Guardar como CSV
df1.to_csv('base_datos_1.csv', index=False)

import pandas as pd

data2 = {
    'FECHA_CORTE': ['20221121', '20221121', '20221121', '20221121', '20221121'],
    'ANP_CATE': ['Reserva Nacional', 'Reserva Nacional', 'Reserva Nacional', 'Reserva Nacional', 'Reserva Nacional'],
    'ANP_CODI': ['RN13.28', 'RN13.29', 'RN13.30', 'RN13.31', 'RN13.32'],
    'ANP_NOMB': ['Punta San Juan', 'Punta Lomas', 'Punta Atico', 'Punta La Chira', 'Punta Hornillos'],
    'ANP_SECT': [None, None, None, None, None],
    'ANP_UBPO': ['Ica', 'Arequipa', 'Arequipa', 'Arequipa', 'Arequipa'],
    'ANP_SULEG': [2968.8, 2404.26, 3467.69, 2436.68, 2684.19],
    'ANP_UICN': ['VI - Uso sostenible de recursos naturales'] * 5,
    'ANP_BALEC': ['D.S. N° 024-2009-MINAM'] * 5,
    'ANP_FELEC': [20091231, 20091231, 20091231, 20091231, 20091231],
    'ANP_BALEM': [None, None, None, None, None],
    'ANP_FELEM': [None, None, None, None, None],
    'ANP_WDPAID': [555544090] * 5,
    'UBIGEO1': [110304, 40311, 40303, 40204, 40207],
    'DEPARTAMENTO1': ['Ica'] * 5,
    'PROVINCIA1': ['NASCA'] * 5,
    'DISTRITO1': ['MARCONA', 'CARAVELI', 'CARAVELI', 'CAMANA', 'CAMANA'],
     'UBIGEO2': [None] * 5,
    'DEPARTAMENTO2': [None] * 5,
    'PROVINCIA2': [None] * 5,
    'DISTRITO2': [None] * 5,
    'UBIGEO3': [None] * 5,
    'DEPARTAMENTO3': [None] * 5,
    'PROVINCIA3': [None] * 5,
    'DISTRITO3': [None] * 5,
    'UBIGEO4': [None] * 5,
    'DEPARTAMENTO4': [None] * 5,
    'PROVINCIA4': [None] * 5,
    'DISTRITO4': [None] * 5,
    'UBIGEO5': [None] * 5,
    'DEPARTAMENTO5': [None] * 5,
    'PROVINCIA5': [None] * 5,
    'DISTRITO5': [None] * 5,
    'UBIGEO6': [None] * 5,
    'DEPARTAMENTO6': [None] * 5,
    'PROVINCIA6': [None] * 5,
    'DISTRITO6': [None] * 5,
        'UBIGEO7': [None] * 5,
    'DEPARTAMENTO7': [None] * 5,
    'PROVINCIA7': [None] * 5,
    'DISTRITO7': [None] * 5,
    'UBIGEO8': [None] * 5,
    'DEPARTAMENTO8': [None] * 5,
    'PROVINCIA8': [None] * 5,
    'DISTRITO8': [None] * 5,
    'UBIGEO9': [None] * 5,
    'DEPARTAMENTO9': [None] * 5,
    'PROVINCIA9': [None] * 5,
    'DISTRITO9': [None] * 5,
    'UBIGEO10': [None] * 5,
    'DEPARTAMENTO10': [None] * 5,
    'PROVINCIA10': [None] * 5,
    'DISTRITO10': [None] * 5,
    'UBIGEO11': [None] * 5,
    'DEPARTAMENTO11': [None] * 5,
    'PROVINCIA11': [None] * 5,
    'DISTRITO11': [None] * 5,
    'UBIGEO12': [None] * 5,
    'DEPARTAMENTO12': [None] * 5,
    'PROVINCIA12': [None] * 5,
    'DISTRITO12': [None] * 5,
    'UBIGEO13': [None] * 5,
    'DEPARTAMENTO13': [None] * 5,
    'PROVINCIA13': [None] * 5,
    'DISTRITO13': [None] * 5,
    'UBIGEO14': [None] * 5,
    'DEPARTAMENTO14': [None] * 5,
    'PROVINCIA14': [None] * 5,
    'DISTRITO14': [None] * 5,
    'UBIGEO15': [None] * 5,
    'DEPARTAMENTO15': [None] * 5,
    'PROVINCIA15': [None] * 5,
    'DISTRITO15': [None] * 5,
    'UBIGEO16': [None] * 5,
    'DEPARTAMENTO16': [None] * 5,
    'PROVINCIA16': [None] * 5,
    'DISTRITO16': [None] * 5,
    'UBIGEO17': [None] * 5,
    'DEPARTAMENTO17': [None] * 5,
    'PROVINCIA17': [None] * 5,
    'DISTRITO17': [None] * 5,
    'UBIGEO18': [None] * 5,
    'DEPARTAMENTO18': [None] * 5,
    'PROVINCIA18': [None] * 5,
    'DISTRITO18': [None] * 5,
    'UBIGEO19': [None] * 5,
    'DEPARTAMENTO19': [None] * 5,
    'PROVINCIA19': [None] * 5,
    'DISTRITO19': [None] * 5,
    'UBIGEO20': [None] * 5,
    'DEPARTAMENTO20': [None] * 5,
    'PROVINCIA20': [None] * 5,
    'DISTRITO20': [None] * 5,
    'UBIGEO21': [None] * 5,
    'DEPARTAMENTO21': [None] * 5,
    'PROVINCIA21': [None] * 5,
    'DISTRITO21': [None] * 5,
    'UBIGEO22': [None] * 5,
    'DEPARTAMENTO22': [None] * 5,
    'PROVINCIA22': [None] * 5,
    'DISTRITO22': [None] * 5,
    'UBIGEO23': [None] * 5,
    'DEPARTAMENTO23': [None] * 5,
    'PROVINCIA23': [None] * 5,
    'DISTRITO23': [None] * 5,
    'UBIGEO24': [None] * 5,
    'DEPARTAMENTO24': [None] * 5,
    'PROVINCIA24': [None] * 5,
    'DISTRITO24': [None] * 5,
    'UBIGEO25': [None] * 5,
    'DEPARTAMENTO25': [None] * 5,
    'PROVINCIA25': [None] * 5,
    'DISTRITO25': [None] * 5,
    'UBIGEO26': [None] * 5,
    'DEPARTAMENTO26': [None] * 5,
    'PROVINCIA26': [None] * 5,
    'DISTRITO26': [None] * 5,
    'UBIGEO27': [None] * 5,
    'DEPARTAMENTO27': [None] * 5,
    'PROVINCIA27': [None] * 5,
    'DISTRITO27': [None] * 5,
    'UBIGEO28': [None] * 5,
    'DEPARTAMENTO28': [None] * 5,
    'PROVINCIA28': [None] * 5,
    'DISTRITO28': [None] * 5,
    'UBIGEO29': [None] * 5,
    'DEPARTAMENTO29': [None] * 5,
    'PROVINCIA29': [None] * 5,
    'DISTRITO29': [None] * 5,
    'UBIGEO30': [None] * 5,
    'DEPARTAMENTO30': [None] * 5,
    'PROVINCIA30': [None] * 5,
    'DISTRITO30': [None] * 5
}

# Crear DataFrame
df2 = pd.DataFrame(data2)

# Guardar como CSV
df2.to_csv('base_datos_2.csv', index=False)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

# Resumen del Proyecto
print("Resumen del Proyecto:")
print("-" * 50)
print("Descripción del DataFrame 1:")
print(df1.info())

print("\nDescripción del DataFrame 2:")
print(df2.info())

# Análisis Exploratorio de Datos (EDA)
# Puedes realizar gráficos, estadísticas descriptivas, etc.
# Aquí se presenta un ejemplo simple con histogramas
print("\nAnálisis Exploratorio de Datos:")
print("-" * 50)

# Histograma de una columna en df2 (ejemplo)
plt.hist(df2['ANP_SULEG'].dropna(), bins=20, color='blue', alpha=0.7)
plt.title('Histograma de ANP_SULEG')
plt.xlabel('Valor')
plt.ylabel('Frecuencia')
plt.show()


plt.hist(df2['ANP_FELEC'].dropna(), bins=20, color='blue', alpha=0.7)
plt.title('Histograma de ANP_FELEC')
plt.xlabel('Valor')
plt.ylabel('Frecuencia')
plt.show()

# Obtener una tabla con los valores únicos en la columna FECHA_CORTE
resumen_fecha_corte = df2['FECHA_CORTE'].value_counts().reset_index()
resumen_fecha_corte.columns = ['FECHA_CORTE', 'FRECUENCIA']

# Mostrar la tabla
print("Tabla de Resumen de FECHA_CORTE:")
print(resumen_fecha_corte)


# Obtener una tabla con el resumen de variables, descripciones y tipos de datos
resumen_variables1 = df1[['VARIABLE']]
resumen_variables2 = df1[['DESCRIPCIÓN']]
resumen_variables3 = df1[['TIPO DE DATO']]
# Mostrar la tabla
print("Tabla de Resumen de Variables:")
print(resumen_variables1)
print(resumen_variables2)
print(resumen_variables3)