# -*- coding: utf-8 -*-
"""CODIGO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EoqtI9TDQ_H5yRRkIax5-bHBVwl11z1f
"""

pip install flask
from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejemplo de Página Web</title>
</head>
<body>
    <h1>Hola, esta es una página de ejemplo en Python</h1>
    <p>¡Bienvenido al mundo de Flask!</p>
</body>
</html>
python app.py

pip install flask



@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/contact')
def contact():
    return render_template('contact.html')



@app.route('/user/<username>')



def show_user_profile(username):
    return f'Usuario {username}'
pip install Flask-WTF
from flask import Flask, render_template
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField

app = Flask(__name__)
app.config['SECRET_KEY'] = 'clave_secreta'  # Cambia esto por una clave segura en un entorno real

class MyForm(FlaskForm):
    name = StringField('Nombre')
    submit = SubmitField('Enviar')

@app.route('/form', methods=['GET', 'POST'])
def form():
    form = MyForm()
    if form.validate_on_submit():
        return f'¡Hola, {form.name.data}!'
    return render_template('form.html', form=form)



<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">